
version: '3'
services:
  api:
    build: 
      context: .
      dockerfile: ./docker/dev/Dockerfile
    ports:
      - 80:80
    volumes:
      - .:/app
  db:
    image: postgres:13.12
    environment:
      POSTGRES_USER: '${DB_USER:-user}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-password}'
      POSTGRES_DB: '${DB_NAME:-db}'
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
